import { useEffect, useState } from 'react'
import { adminGetCommunity, adminModeratePost, adminModerateResponse, type AdminCommunityPayload } from '../../services/api'

const initial:AdminCommunityPayload={summary:{totalPosts:0,reportedPosts:0,reportedResponses:0},posts:[],pagination:{page:1,pageSize:10,total:0,totalPages:1}}
const SearchIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>
const MessageIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"/></svg>
const InboxIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/></svg>
function formatDate(value:string){return new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(value))}
function statusLabel(value:string){return value==='PUBLISHED'?'Active':value==='HIDDEN'?'Hidden':value==='REMOVED'?'Deleted':value}

export function CommunityPage(){
 const [data,setData]=useState(initial),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[reportedOnly,setReportedOnly]=useState(false),[page,setPage]=useState(1),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 async function load(){setLoading(true);try{setData(await adminGetCommunity({search,status,reportedOnly,page,pageSize:10}));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load community')}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(load,160);return()=>clearTimeout(t)},[search,status,reportedOnly,page]);useEffect(()=>setPage(1),[search,status,reportedOnly])
 async function act(id:string,next:'PUBLISHED'|'HIDDEN'|'REMOVED'){try{await adminModeratePost(id,{status:next,clearReport:next==='PUBLISHED'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to moderate post')}}
 async function actResponse(id:string,next:'PUBLISHED'|'HIDDEN'|'REMOVED'){try{await adminModerateResponse(id,{status:next,clearReport:next==='PUBLISHED'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to moderate response')}}
 const start=data.pagination.total===0?0:(data.pagination.page-1)*data.pagination.pageSize+1
 const end=Math.min(data.pagination.page*data.pagination.pageSize,data.pagination.total)
 const pages=Array.from({length:data.pagination.totalPages},(_,i)=>i+1).filter(p=>p===1||p===data.pagination.totalPages||Math.abs(p-page)<=1)
 return <main className="admin-community-reference">
   <header className="acm-hero"><div><span className="acm-kicker">Admin panel</span><h1>Community</h1><p>A refined review space for browsing active discussions and resolving reported posts and responses.</p></div><div className="acm-moderation"><MessageIcon/><b>Moderation</b></div></header>
   <section className="acm-stats" aria-label="Community summary"><article><span>Total Posts</span><strong>{data.summary.totalPosts}</strong><p>Published community conversations across the forum.</p></article><article><span>Reported Posts</span><strong>{data.summary.reportedPosts}</strong><p>Unique posts currently surfaced for careful review.</p></article><article><span>Reported Responses</span><strong>{data.summary.reportedResponses}</strong><p>Replies awaiting conversation-level review.</p></article></section>
   <section className="acm-panel"><div className="acm-heading"><span className="acm-kicker">Community</span><h2>Posts Management</h2><p>Browse active discussions and resolve reported posts and responses.</p></div>
    <section className="acm-filters" aria-label="Community filters"><label className="acm-search"><SearchIcon/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by author, category, or post" type="search"/></label><label className="acm-select"><select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Filter community posts"><option value="">Post Status</option><option value="PUBLISHED">Active Posts</option><option value="HIDDEN">Hidden Posts</option><option value="REMOVED">Deleted Posts</option></select><i/></label><label className="acm-reported"><span>Show Reported Only</span><input className="sr-only" type="checkbox" checked={reportedOnly} onChange={e=>setReportedOnly(e.target.checked)}/><span className={`acm-toggle ${reportedOnly?'on':''}`}><i/></span></label></section>
    {error&&<div className="hs-error">{error}</div>}
    {loading?<div className="acm-empty"><div className="acm-empty-icon"><InboxIcon/></div><h3>Loading community posts…</h3></div>:data.posts.length===0?<div className="acm-empty"><div className="acm-empty-icon"><InboxIcon/></div><h3>No community posts found</h3><p>Forum posts will appear here once members start sharing stories.</p></div>:<div className="acm-posts">{data.posts.map(post=><article className="acm-post" key={post.id}><div className="acm-post-head"><div><span className="acm-category">{post.category||'Community'}</span><h3>{post.title}</h3><p className="acm-meta">By <b>{post.authorName}</b> · {formatDate(post.createdAt)} · {post.responses.length} response{post.responses.length===1?'':'s'}</p></div><div className="acm-badges"><span className={`acm-status ${post.status.toLowerCase()}`}>{statusLabel(post.status)}</span>{post.isReported&&<span className="acm-report">{post.reportCount} report{post.reportCount===1?'':'s'}</span>}</div></div><p className="acm-body">{post.body}</p><div className="acm-actions"><button className="publish" onClick={()=>act(post.id,'PUBLISHED')}>Publish</button><button onClick={()=>act(post.id,'HIDDEN')}>Hide</button><button className="danger" onClick={()=>act(post.id,'REMOVED')}>Remove</button></div>{post.responses.length>0&&<div className="acm-responses"><span className="acm-kicker">Responses</span>{post.responses.map(response=><div className="acm-response" key={response.id}><div><b>{response.authorName}</b><small>{formatDate(response.createdAt)}</small><p>{response.body}</p></div><div><span className={`acm-status ${response.status.toLowerCase()}`}>{statusLabel(response.status)}</span>{response.isReported&&<span className="acm-report">{response.reportCount} report{response.reportCount===1?'':'s'}</span>}<div className="acm-response-actions"><button onClick={()=>actResponse(response.id,'PUBLISHED')}>Publish</button><button onClick={()=>actResponse(response.id,'HIDDEN')}>Hide</button><button onClick={()=>actResponse(response.id,'REMOVED')}>Remove</button></div></div></div>)}</div>}</article>)}</div>}
    {data.pagination.total>0&&<footer className="acm-pagination"><div>Showing <b>{start}-{end}</b> of <b>{data.pagination.total}</b></div><nav><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button>{pages.map((p,i)=><span key={p}>{i>0&&pages[i-1]!==p-1?<i>…</i>:null}<button className={p===page?'current':''} onClick={()=>setPage(p)}>{p}</button></span>)}<button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav></footer>}
   </section>
 </main>
}
