import { useMemo, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { AdminHero, Panel } from '../components/AdminLayout'
import { adminCreateChallenge, type AdminChallengeReminder } from '../../services/api'

type DraftReminder=AdminChallengeReminder & {key:string; reminderDate:string; emailEnabled:boolean; smsEnabled:boolean; emailSubject?:string; emailMessage?:string; smsMessage?:string}
const XIcon=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 6 6 18M6 6l12 12"/></svg>
export function CreateChallengePage(){
 const navigate=useNavigate(), fileRef=useRef<HTMLInputElement>(null)
 const [title,setTitle]=useState(''),[challengeMonth,setChallengeMonth]=useState(''),[overview,setOverview]=useState(''),[goal,setGoal]=useState(''),[howToComplete,setHowToComplete]=useState(''),[relationshipBenefit,setRelationshipBenefit]=useState(''),[image,setImage]=useState<File|null>(null),[imageUrl,setImageUrl]=useState(''),[reminders,setReminders]=useState<DraftReminder[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState(''),[reminderOpen,setReminderOpen]=useState(false)
 const [dates,setDates]=useState<string[]>([]),[sendTime,setSendTime]=useState('09:00'),[ruleActive,setRuleActive]=useState(true),[emailEnabled,setEmailEnabled]=useState(true),[smsEnabled,setSmsEnabled]=useState(false),[emailSubject,setEmailSubject]=useState(''),[emailMessage,setEmailMessage]=useState(''),[smsMessage,setSmsMessage]=useState('')
 const canSave=useMemo(()=>!!(title.trim()&&challengeMonth&&overview.trim()&&goal.trim()&&howToComplete.trim()&&relationshipBenefit.trim()),[title,challengeMonth,overview,goal,howToComplete,relationshipBenefit])
 const monthBounds=useMemo(()=>{if(!challengeMonth)return {min:'',max:''};const [y,m]=challengeMonth.split('-').map(Number);const last=new Date(Date.UTC(y,m,0)).getUTCDate();return {min:`${challengeMonth}-01`,max:`${challengeMonth}-${String(last).padStart(2,'0')}`}},[challengeMonth])
 function choose(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Use a JPG, PNG, or WebP image.');return}if(file.size>5*1024*1024){setError('Challenge image must be 5 MB or smaller.');return}setImage(file);setImageUrl(URL.createObjectURL(file));setError('')}
 function openReminder(){const d=monthBounds.min||'';setDates([d]);setSendTime('09:00');setRuleActive(true);setEmailEnabled(true);setSmsEnabled(false);setEmailSubject('');setEmailMessage('');setSmsMessage('');setReminderOpen(true)}
 function saveRule(){if(!challengeMonth){setError('Choose the Challenge Month before adding reminder rules.');setReminderOpen(false);return}const valid=dates.filter(Boolean);if(!valid.length||(!emailEnabled&&!smsEnabled))return;const rows:DraftReminder[]=[];valid.forEach(date=>{const day=Number(date.slice(-2)); if(emailEnabled)rows.push({key:crypto.randomUUID(),reminderDate:date,dayOfMonth:day,timeOfDay:sendTime,channel:'EMAIL',isActive:ruleActive,emailEnabled:true,smsEnabled:false,emailSubject,emailMessage,smsMessage});if(smsEnabled)rows.push({key:crypto.randomUUID(),reminderDate:date,dayOfMonth:day,timeOfDay:sendTime,channel:'SMS',isActive:ruleActive,emailEnabled:false,smsEnabled:true,emailSubject,emailMessage,smsMessage})});setReminders(r=>[...r,...rows]);setReminderOpen(false)}
 function removeReminder(key:string){setReminders(r=>r.filter(x=>x.key!==key))}
 async function submit(e?:React.FormEvent){e?.preventDefault();if(!canSave)return;setSaving(true);setError('');try{const fd=new FormData();fd.set('title',title);fd.set('challengeMonth',challengeMonth);fd.set('overview',overview);fd.set('goal',goal);fd.set('howToComplete',howToComplete);fd.set('relationshipBenefit',relationshipBenefit);fd.set('status','DRAFT');fd.set('reminders',JSON.stringify(reminders.map(({key,reminderDate,emailEnabled,smsEnabled,...x})=>x)));if(image)fd.set('image',image);await adminCreateChallenge(fd);navigate('/admin/challenges')}catch(e){setError(e instanceof Error?e.message:'Unable to create challenge')}finally{setSaving(false)}}
 return <>
  <AdminHero eyebrow="ADMIN CHALLENGES" title="Create Challenge" copy="Create and maintain monthly challenge notes, artwork, publishing windows, and automated reminder rules." action={<Link className="hs-outline" to="/admin/challenges">Back to Challenges</Link>}/>
  <div className="hs-create-challenge-grid">
   <form onSubmit={submit}><Panel className="hs-challenge-form-panel"><span className="hs-eyebrow">BASICS</span><h2>Challenge Content</h2>
    <label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label>
    <label>Challenge Month<input type="month" value={challengeMonth} onChange={e=>setChallengeMonth(e.target.value)}/></label>
    <label>Overview<textarea value={overview} onChange={e=>setOverview(e.target.value)}/></label>
    <label>Goal<textarea value={goal} onChange={e=>setGoal(e.target.value)}/></label><label>How To Complete<textarea value={howToComplete} onChange={e=>setHowToComplete(e.target.value)}/></label><label>Relationship Benefit<textarea value={relationshipBenefit} onChange={e=>setRelationshipBenefit(e.target.value)}/></label>
    {error&&<div className="hs-error">{error}</div>}<div className="hs-form-actions"><button type="submit" className="hs-btn" disabled={!canSave||saving}>{saving?'Creating…':'Create Challenge'}</button></div>
   </Panel></form>
   <div className="hs-challenge-side">
    <Panel><span className="hs-eyebrow">ARTWORK</span><h2>Challenge Image</h2><div className="hs-artwork-preview">{imageUrl?<img src={imageUrl} alt="Challenge preview"/>:<span>No image uploaded yet</span>}</div><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>choose(e.target.files?.[0])}/><button type="button" className="hs-outline" onClick={()=>fileRef.current?.click()}>Choose Image</button><p>Selected artwork will be uploaded automatically right after the challenge is created.</p><p>Use a JPG, PNG, or WebP image up to 5 MB. Minimum size is 800 × 600 pixels.</p></Panel>
    <Panel className="hs-reminder-panel"><div className="hs-reminder-heading"><span className="hs-eyebrow">REMINDER RULES</span><h2>Automated Reminders</h2><button type="button" className="hs-btn" onClick={openReminder}>Add Reminder Rule</button></div>{reminders.length===0?<div className="hs-reminder-empty"><h2>No reminder rules yet</h2><p>Create one or more monthly reminder schedules for this challenge.</p></div>:<div className="hs-reminders">{reminders.map(r=><div className="hs-reminder-card" key={r.key}><div><b>{r.channel} · Day {r.dayOfMonth}</b><small>{r.timeOfDay} UTC · {r.isActive?'Active':'Inactive'}</small></div><button type="button" aria-label="Remove reminder" onClick={()=>removeReminder(r.key)}><XIcon/></button></div>)}</div>}</Panel>
   </div>
  </div>
  {reminderOpen&&<div className="hs-modal-backdrop" role="dialog" aria-modal="true"><div className="hs-reminder-modal"><div className="hs-reminder-modal-head"><button className="hs-modal-x" type="button" onClick={()=>setReminderOpen(false)}><XIcon/></button><div className="hs-modal-icon">▣</div><span className="hs-eyebrow">PLEASE CONFIRM</span><h2>Create reminder rule</h2><p>Configure the reminder schedule, delivery channels, and optional message overrides.</p></div><div className="hs-reminder-modal-body">
   <section><span className="hs-modal-section-label">SCHEDULE</span><div className="hs-date-title"><b>Reminder Date</b><button type="button" onClick={()=>setDates(d=>[...d,monthBounds.min])}>+</button></div>{dates.map((d,i)=><div className="hs-date-row" key={i}><input type="date" min={monthBounds.min} max={monthBounds.max} value={d} onChange={e=>setDates(a=>a.map((x,j)=>j===i?e.target.value:x))}/><button type="button" disabled={dates.length===1} onClick={()=>setDates(a=>a.filter((_,j)=>j!==i))}><XIcon/></button></div>)}<div className="hs-two"><label>Send Time<input type="time" value={sendTime} onChange={e=>setSendTime(e.target.value)}/></label><label className="hs-switch-row"><input type="checkbox" checked={ruleActive} onChange={e=>setRuleActive(e.target.checked)}/><span>Active</span></label></div><div className="hs-utc-note"><b>Note:</b> Reminder time will be saved in UTC (Coordinated Universal Time).</div></section>
   <section><span className="hs-modal-section-label">DELIVERY CHANNELS</span><div className="hs-two hs-channel-box"><label className="hs-switch-row"><input type="checkbox" checked={emailEnabled} onChange={e=>setEmailEnabled(e.target.checked)}/><span>Email Enabled</span></label><label className="hs-switch-row"><input type="checkbox" checked={smsEnabled} onChange={e=>setSmsEnabled(e.target.checked)}/><span>SMS Enabled</span></label></div></section>
   <section><span className="hs-modal-section-label">MESSAGE OVERRIDES</span><label>Email Subject<input placeholder="Subject for reminder emails" value={emailSubject} onChange={e=>setEmailSubject(e.target.value)}/></label><label>Email Message<textarea placeholder="Custom body for the reminder email" value={emailMessage} onChange={e=>setEmailMessage(e.target.value)}/></label><label>SMS Message<textarea placeholder="Custom SMS copy for this reminder" value={smsMessage} onChange={e=>setSmsMessage(e.target.value)}/></label></section>
  </div><div className="hs-reminder-modal-foot"><button type="button" className="hs-outline" onClick={()=>setReminderOpen(false)}>Cancel</button><button type="button" className="hs-save-rule" disabled={!dates.some(Boolean)||(!emailEnabled&&!smsEnabled)} onClick={saveRule}>Save Rule</button></div></div></div>}
 </>
}
