import { useEffect, useMemo, useState } from 'react'
import { adminCreateNotification, adminGetNotifications, adminGetUsers, type AdminNotificationJob, type AdminUser } from '../../services/api'

const fmt=(v:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))
const SearchIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg>
const MailIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect x="2" y="4" width="20" height="16" rx="2"/></svg>
const SmsIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z"/><path d="M7 11h10"/><path d="M7 15h6"/><path d="M7 7h8"/></svg>
const BellIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M10.268 21a2 2 0 0 0 3.464 0"/><path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326"/></svg>
const SendIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z"/><path d="m21.854 2.147-10.94 10.939"/></svg>
const ResetIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>

export function NotificationsPage(){
 const [channel,setChannel]=useState<'EMAIL'|'SMS'>('EMAIL')
 const [audience,setAudience]=useState<'SINGLE_USER'|'SUBSCRIBERS_ONLY'|'ALL_USERS'>('SINGLE_USER')
 const [subject,setSubject]=useState(''),[recipientEmail,setRecipientEmail]=useState(''),[recipientPhone,setRecipientPhone]=useState(''),[message,setMessage]=useState('')
 const [userSearch,setUserSearch]=useState(''),[users,setUsers]=useState<AdminUser[]>([]),[selected,setSelected]=useState<AdminUser|null>(null),[userPage,setUserPage]=useState(1),[userPages,setUserPages]=useState(1)
 const [jobs,setJobs]=useState<AdminNotificationJob[]>([]),[jobPagination,setJobPagination]=useState({page:1,pageSize:10,total:0,totalPages:1}),[jobPage,setJobPage]=useState(1),[jobSearch,setJobSearch]=useState(''),[jobStatus,setJobStatus]=useState(''),[jobAudience,setJobAudience]=useState('')
 const [error,setError]=useState(''),[sending,setSending]=useState(false)

 async function loadJobs(){try{const result=await adminGetNotifications({search:jobSearch,status:jobStatus,audience:jobAudience,page:jobPage,pageSize:10});setJobs(result.jobs??[]);setJobPagination(result.pagination??{page:1,pageSize:10,total:0,totalPages:1})}catch(e){setError(e instanceof Error?e.message:'Unable to load jobs')}}
 useEffect(()=>{const t=setTimeout(loadJobs,160);return()=>clearTimeout(t)},[jobSearch,jobStatus,jobAudience,jobPage])
 useEffect(()=>setJobPage(1),[jobSearch,jobStatus,jobAudience])
 useEffect(()=>{const t=setTimeout(async()=>{try{const result=await adminGetUsers({search:userSearch,page:userPage,pageSize:5});setUsers(result.users??[]);setUserPages(result.pagination?.totalPages??1)}catch{}},160);return()=>clearTimeout(t)},[userSearch,userPage])
 useEffect(()=>setUserPage(1),[userSearch])

 const summary=useMemo(()=>({channel,audience,selected:selected?.fullName??'Not selected',length:message.length}),[channel,audience,selected,message])
 async function send(){setError('');setSending(true);try{await adminCreateNotification({channel,audience,selectedUserId:selected?.id??null,recipientEmail:channel==='EMAIL'?(recipientEmail||null):null,recipientPhone:channel==='SMS'?(recipientPhone||null):null,subject:channel==='EMAIL'?subject:null,message});setSubject('');setRecipientEmail('');setRecipientPhone('');setMessage('');setSelected(null);await loadJobs()}catch(e){setError(e instanceof Error?e.message:'Unable to create notification')}finally{setSending(false)}}
 function reset(){setChannel('EMAIL');setAudience('SINGLE_USER');setSubject('');setRecipientEmail('');setRecipientPhone('');setMessage('');setSelected(null);setError('')}
 return <main className="admin-notifications-reference">
  <header className="an-hero"><div><span className="an-kicker">Admin panel</span><h1>Notifications</h1><p>Send careful email and SMS updates to users, subscribers, and selected recipients.</p></div><span className="an-composer-badge"><BellIcon/>Composer</span></header>

  <section className="an-layout">
   <section className="an-panel an-compose"><div className="an-section-title"><span className="an-kicker">Message composer</span><h2>Create Notification</h2><p>Choose the channel, define the audience, and prepare a clear message.</p></div>
    <div className="an-form-stack">
     <div><span className="an-label">Notification Type</span><div className="an-type-grid"><button type="button" className={channel==='EMAIL'?'active':''} onClick={()=>setChannel('EMAIL')}><span><MailIcon/>Email</span><small>Send a carefully written email update.</small></button><button type="button" className={channel==='SMS'?'active':''} onClick={()=>setChannel('SMS')}><span><SmsIcon/>SMS</span><small>Send a short SMS to a user or segment.</small></button></div></div>
     <div><span className="an-label">Recipient Scope</span><div className="an-scope-grid"><button type="button" className={audience==='SINGLE_USER'?'active':''} onClick={()=>setAudience('SINGLE_USER')}>Single User</button><button type="button" className={audience==='SUBSCRIBERS_ONLY'?'active':''} onClick={()=>setAudience('SUBSCRIBERS_ONLY')}>Subscribers Only</button><button type="button" className={audience==='ALL_USERS'?'active':''} onClick={()=>setAudience('ALL_USERS')}>All Users</button></div></div>
     {channel==='EMAIL'&&<label className="an-field"><span>Subject</span><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Example: Your order update from Heartstring Notes"/></label>}
     {audience==='SINGLE_USER'&&<label className="an-field"><span>{channel==='EMAIL'?'Recipient Email':'Recipient Phone'}</span><input value={channel==='EMAIL'?recipientEmail:recipientPhone} onChange={e=>channel==='EMAIL'?setRecipientEmail(e.target.value):setRecipientPhone(e.target.value)} placeholder={channel==='EMAIL'?'name@example.com':'+1 415 555 0134'} type={channel==='EMAIL'?'email':'tel'}/></label>}
     <label className="an-field"><span>Message</span><textarea value={message} onChange={e=>setMessage(e.target.value)} rows={7} placeholder={channel==='EMAIL'?'Write the email body.':'Write the SMS message.'}/></label>
     {channel==='EMAIL'?<div className="an-limit"><strong>Sending limits</strong><p>Up to <b>300 emails</b> can be sent at one time, and up to <b>3,000 emails</b> can be sent in a day. If the daily limit is reached, the remaining emails will continue automatically on the next day.</p></div>:<div className="an-limit"><strong>SMS Sending limits</strong><p>Each SMS will be sent with a <b>2-second gap</b>. After <b>300 messages</b>, sending will pause for <b>15 minutes</b> and then resume automatically.</p></div>}
     {error&&<div className="hs-error">{error}</div>}
     <div className="an-actions"><div><em className="green">{channel==='EMAIL'?'Email':'SMS'}</em><em>{audience.replaceAll('_',' ')}</em></div><div><button type="button" className="secondary" onClick={reset}><ResetIcon/>Reset</button><button type="button" className="primary" disabled={sending||!message.trim()} onClick={send}><SendIcon/>{sending?'Saving…':'Send Notification'}</button></div></div>
    </div>
   </section>

   <div className="an-side">
    <section className="an-panel"><div className="an-section-title"><span className="an-kicker">Recipient lookup</span><h2>Select User</h2><p>Search the local directory preview and fill contact fields quickly.</p></div><div className="an-user-search"><SearchIcon/><input value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Search by name, email, or phone"/></div><div className="an-user-list">{users.length===0?<div className="an-user-empty">No users found.</div>:users.map(u=><button key={u.id} className={selected?.id===u.id?'selected':''} onClick={()=>{setSelected(u);setRecipientEmail(u.email);setRecipientPhone(u.phone??'')}}><span><strong>{u.fullName}</strong><small>{channel==='SMS'?(u.phone||'No phone number'):u.email}</small>{channel==='SMS'&&u.phone&&<small>{u.email}</small>}</span><em>{u.subscriptionStatus}</em></button>)}</div><nav className="an-user-pages"><button disabled={userPage<=1} onClick={()=>setUserPage(p=>p-1)}>Previous</button><span>{userPage}</span><button disabled={userPage>=userPages} onClick={()=>setUserPage(p=>p+1)}>Next</button></nav></section>
    <section className="an-panel"><div className="an-section-title"><span className="an-kicker">Preview</span><h2>Delivery Summary</h2><p>A quick final check before the notification is sent.</p></div><dl className="an-summary"><div><dt>Channel</dt><dd>{summary.channel==='EMAIL'?'Email':'SMS'}</dd></div><div><dt>Audience</dt><dd>{summary.audience.replaceAll('_',' ')}</dd></div><div><dt>Selected User</dt><dd>{summary.selected}</dd></div><div><dt>Message Length</dt><dd>{summary.length} chars</dd></div></dl></section>
   </div>
  </section>

  <section className="an-panel an-history"><div className="an-section-title"><span className="an-kicker">History</span><h2>Notification Jobs</h2><p>Review sent and queued notification jobs with quick filters for follow-up.</p></div><div className="an-history-filter"><label><SearchIcon/><input value={jobSearch} onChange={e=>setJobSearch(e.target.value)} placeholder="Search by subject"/></label><select value={jobStatus} onChange={e=>setJobStatus(e.target.value)}><option value="">Job Status</option><option value="QUEUED">Queued</option><option value="PROCESSING">Processing</option><option value="COMPLETED">Completed</option><option value="FAILED">Failed</option><option value="CANCELLED">Cancelled</option></select><select value={jobAudience} onChange={e=>setJobAudience(e.target.value)}><option value="">Job Audience</option><option value="SINGLE_USER">Single User</option><option value="SUBSCRIBERS_ONLY">Subscribers Only</option><option value="ALL_USERS">All Users</option></select><button type="button" onClick={loadJobs}><ResetIcon/>Refresh</button></div>
   {jobs.length===0?<div className="an-empty"><h3>No notification jobs found</h3><p>Send a notification or adjust the filters to see job history.</p></div>:<div className="an-job-table"><div className="an-job-row head"><span>Subject / Message</span><span>Channel</span><span>Audience</span><span>Recipients</span><span>Status</span><span>Created</span></div>{jobs.map(j=><div className="an-job-row" key={j.id}><span><b>{j.subject||j.message.slice(0,50)}</b><small>{j.selectedUser?.fullName||j.recipientEmail||'Segment delivery'}</small></span><span>{j.channel}</span><span>{j.audience.replaceAll('_',' ')}</span><span>{j.totalRecipients}</span><span><em>{j.status}</em></span><span>{fmt(j.createdAt)}</span></div>)}</div>}
   <footer className="an-pagination"><div>Showing <b>{jobPagination.total===0?0:(jobPagination.page-1)*jobPagination.pageSize+1}-{Math.min(jobPagination.page*jobPagination.pageSize,jobPagination.total)}</b> of <b>{jobPagination.total}</b></div><nav><button disabled={jobPage<=1} onClick={()=>setJobPage(p=>p-1)}>Previous</button><span>{jobPage}</span><button disabled={jobPage>=jobPagination.totalPages} onClick={()=>setJobPage(p=>p+1)}>Next</button></nav></footer>
  </section>
 </main>
}
