import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { adminDownloadPersonalizedOrderPdf, adminGetOrder, adminSetOrderDeliveryDate, adminSetOrderQuote, adminSetOrderReviewed, adminSetOrderStatus, type AdminCardOrder } from '../../services/api'

const money=(n?:number|null)=>n==null?'Pending':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
const dateFmt=(v?:string|null,withTime=false)=>v?new Intl.DateTimeFormat('en-US',withTime?{month:'short',day:'2-digit',year:'numeric',hour:'numeric',minute:'2-digit'}:{month:'short',day:'2-digit',year:'numeric'}).format(new Date(v)):'Not set'
const label=(v:string)=>v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase())
const dateInput=(v?:string|null)=>v?new Date(v).toISOString().slice(0,10):''

export function OrderDetailPage(){
 const {orderId=''}=useParams(),[order,setOrder]=useState<AdminCardOrder|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[shippingFee,setShippingFee]=useState(''),[deliveryDate,setDeliveryDate]=useState(''),[pdfBusy,setPdfBusy]=useState(false)
 async function load(){try{setOrder(await adminGetOrder(orderId));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load order')}}
 useEffect(()=>{load()},[orderId])
 useEffect(()=>{if(order){setShippingFee(order.shippingFee==null?'':String(order.shippingFee));setDeliveryDate(dateInput(order.estimatedDeliveryDate))}},[order])
 async function setStatus(status:AdminCardOrder['status']){if(!order)return;setSaving(true);try{setOrder(await adminSetOrderStatus(order.id,status));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to update order')}finally{setSaving(false)}}
 async function saveQuote(){if(!order)return;const fee=Number(shippingFee);if(!Number.isFinite(fee)||fee<0){setError('Enter a valid shipping fee.');return}setSaving(true);try{setOrder(await adminSetOrderQuote(order.id,fee));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to update shipping quote')}finally{setSaving(false)}}
 async function toggleReviewed(){if(!order)return;setSaving(true);try{setOrder(await adminSetOrderReviewed(order.id,!order.reviewed));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to update order')}finally{setSaving(false)}}
 async function saveDeliveryDate(){if(!order)return;setSaving(true);try{setOrder(await adminSetOrderDeliveryDate(order.id,deliveryDate||null));setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to update estimated delivery date')}finally{setSaving(false)}}
 async function downloadPrintPdf(){if(!order)return;setPdfBusy(true);setError('');try{await adminDownloadPersonalizedOrderPdf(order.id)}catch(e){setError(e instanceof Error?e.message:'Unable to generate personalized print PDF')}finally{setPdfBusy(false)}}
 if(!order)return <main className="admin-order-detail-reference"><div className="aod-empty">{error||'Loading order…'}</div></main>
 const paymentStatus=order.paymentStatus||'UNPAID'
 return <main className="admin-order-detail-reference">
  <header className="aod-hero"><div><span className="aod-kicker">Admin panel</span><h1>Order Detail</h1><p>Review shipping details, personalization, set the fee, update status, and manage fulfilment in one view.</p></div><Link className="aod-back" to="/admin/orders">← Back to Orders</Link></header>
  {error&&<div className="hs-error">{error}</div>}
  <section className="aod-grid">
   <section className="aod-panel aod-overview"><div className="aod-heading"><span className="aod-kicker">Order summary</span><h2>Order Overview</h2><p>A clear snapshot of the order, subscriber context, and current handling state.</p></div><div className="aod-summary">
    <article><span>Order ID</span><b className="small-id">{order.orderNumber||order.id}</b></article><article><span>User Name</span><b>{order.customerName}</b><small>{order.customerEmail}</small></article><article><span>Date Placed</span><b>{dateFmt(order.placedAt)}</b><small>{dateFmt(order.placedAt,true)}</small></article><article><span>Current Status</span><b><i className={`aod-status ${order.status.toLowerCase()}`}>{label(order.status)}</i></b><small>{order.reviewed?'Reviewed by admin':'Awaiting admin review'}</small></article>
   </div></section>

   <section className="aod-panel aod-items"><div className="aod-heading"><span className="aod-kicker">Ordered items</span><h2>Cards in This Order</h2><p>Card details and the personalization that will appear on the finished card.</p></div><article className="aod-card-row"><div className="aod-card-art"><div><h3>{order.cardTitle}</h3><p>{order.cardCategory||'Physical Card'}</p></div></div><div className="aod-card-info"><h3>{order.cardTitle}</h3><p>{order.cardCategory||'Physical Card'} <span>Qty {order.quantity}</span></p><div className="aod-info-grid"><div><span>Recipient</span><b>{order.shippingName||order.customerName}</b></div><div><span>Collection</span><b>{order.cardCategory||'Physical Card'}</b></div></div><div className="aod-personal-inline"><div><span>To / Bottom Left</span><b>{order.personalizationRecipient||'Not provided'}</b></div><div><span>From / Bottom Right</span><b>{order.personalizationSender||'Not provided'}</b></div></div></div><i className="aod-qty">Qty {order.quantity}</i></article></section>

   <section className="aod-panel aod-handling"><div className="aod-heading"><span className="aod-kicker">Order handling</span><h2>Fee &amp; Status</h2><p>Set the shipping fee and choose the order status.</p></div><label>Shipping Fee<div className="aod-money-input"><span>$</span><input type="number" min="0" step="0.01" value={shippingFee} onChange={e=>setShippingFee(e.target.value)}/></div></label><label>Order Status<select disabled={saving} value={order.status} onChange={e=>setStatus(e.target.value as AdminCardOrder['status'])}><option value="PLACED">Placed</option><option value="QUOTED">Quoted</option><option value="IN_PROGRESS">In Progress</option><option value="SHIPPED">Shipped</option><option value="DELIVERED">Delivered</option><option value="CANCELLED">Cancelled</option></select></label><div className="aod-actions"><button disabled={saving} onClick={saveQuote}>Save Changes</button><button className="outline" disabled={saving} onClick={toggleReviewed}>{order.reviewed?'Mark Unreviewed':'Mark Reviewed'}</button></div></section>

   <section className="aod-panel aod-personalization"><div className="aod-heading"><span className="aod-kicker">Personalization</span><h2>Card Footer</h2><p>These names are printed at the bottom of the card without interfering with the poem or logo.</p></div><div className="aod-personal-boxes"><div><span>Bottom Left</span><strong>For: {order.personalizationRecipient||'Not provided'}</strong></div><div><span>Bottom Right</span><strong>With Love: {order.personalizationSender||'Not provided'}</strong></div></div><button className="aod-download" disabled={pdfBusy||!order.personalizationRecipient||!order.personalizationSender} onClick={downloadPrintPdf}>{pdfBusy?'Creating print PDF…':'Download Personalized Print PDF'}</button></section>

   <section className="aod-panel aod-shipping"><div className="aod-heading"><span className="aod-kicker">Shipping information</span><h2>Recipient &amp; Address</h2><p>Shipping details for review before fulfillment continues.</p></div><div className="aod-info-grid"><div><span>Recipient Name</span><b>{order.shippingName||order.customerName}</b></div><div><span>Tracking Number</span><b>{order.trackingNumber||'Not available'}</b></div><div className="wide"><span>Shipping Address</span><b>{order.shippingAddress||'No shipping address stored yet.'}</b></div><div className="wide"><span>Notes</span><b>{order.shippingNote||'Not provided'}</b></div></div></section>

   <section className="aod-panel aod-delivery"><div className="aod-heading"><span className="aod-kicker">Estimated delivery</span><h2>Delivery Date</h2><p>Set an estimated delivery date to keep the customer timeline current.</p></div><label className="aod-field">Estimated Delivery Date<input type="date" value={deliveryDate} onChange={e=>setDeliveryDate(e.target.value)}/></label><div className="aod-date-current"><span>Current Date</span><b>{dateFmt(order.estimatedDeliveryDate)}</b></div><div className="aod-save-row"><button disabled={saving||deliveryDate===dateInput(order.estimatedDeliveryDate)} onClick={saveDeliveryDate}>Save Date</button></div></section>

   <section className="aod-panel aod-totals"><div className="aod-heading"><span className="aod-kicker">Totals</span><h2>Billing Snapshot</h2><p>Live preview of the order total based on current inputs.</p></div><div className="aod-total-list"><div><span>Each Card Price</span><b>{money(order.cardPrice)}</b></div><div><span>Cards Subtotal</span><b>{money(order.subtotal)} ({order.quantity} card{order.quantity===1?'':'s'})</b></div><div><span>Printing Fee</span><b>{money(order.printingFee)}</b></div><div><span>Shipping Fee</span><b>{money(order.shippingFee)}</b></div></div><div className="aod-total"><span>Preview Total</span><strong>{money(order.totalAmount)}</strong></div></section>

   <section className="aod-panel aod-payment"><div className="aod-heading"><span className="aod-kicker">Payment</span><h2>Payment Details</h2><p>Payment state, invoice reference, and provider lookup details.</p></div><div className="aod-payment-status"><div><span>Payment Status</span><small>Current customer payment state.</small></div><i className={`aod-pay-badge ${paymentStatus.toLowerCase()}`}>{paymentStatus}</i></div><div className="aod-payment-list"><div><span>Receipt</span><b>{order.paymentReceipt||'-'}</b></div><div><span>Payment Date</span><b>{order.paymentDate?dateFmt(order.paymentDate,true):'-'}</b></div><div><span>Payment Method</span><b>{order.paymentMethod||'-'}</b></div><div><span>Refund Status</span><b>{order.refundStatus||'-'}</b></div><div><span>Stripe Payment ID</span><b className="small-id">{order.stripePaymentId||'-'}</b></div></div><div className="aod-payment-note">{order.shippingFee==null?'Add the shipping fee first so the customer can receive the final payment amount.':paymentStatus==='UNPAID'?'Shipping fee added. Waiting for customer payment.':'Payment information is available for this order.'}</div></section>

   <section className="aod-panel aod-feedback"><div className="aod-heading"><span className="aod-kicker">Feedback</span><h2>Order Feedback</h2><p>Customer feedback for the order</p></div><div className="aod-feedback-box"><div className="aod-rating"><span>Rating:</span><strong aria-label={order.feedbackRating?`${order.feedbackRating} out of 5 stars`:'No rating'}>{[1,2,3,4,5].map(n=><i key={n} className={order.feedbackRating&&n<=order.feedbackRating?'filled':''}>★</i>)}</strong></div><p>{order.feedbackText||'No written feedback provided.'}</p></div></section>
  </section>
 </main>
}
