import { FormEvent, useEffect, useMemo, useState } from 'react'
import { AdminHero, AdminPagination, Panel, StatCard } from '../components/AdminLayout'
import { adminCreateScavengerLocation, adminDeleteScavengerLocation, adminGetScavengerLocations, adminSetScavengerLocationStatus, adminUpdateScavengerLocation, type ScavengerLocation } from '../../services/api'

const empty={name:'',description:'',icon:'',sortOrder:0,isActive:true,image:null as File|null}
function Pencil(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z"/></svg>}
function Trash(){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6M10 11v5M14 11v5"/></svg>}
export function AdminScavengerHuntPage(){
 const [items,setItems]=useState<ScavengerLocation[]>([]),[query,setQuery]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<ScavengerLocation|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[del,setDel]=useState<ScavengerLocation|null>(null)
 const refresh=async()=>{try{setItems(await adminGetScavengerLocations());setError('')}catch(e){setError(e instanceof Error?e.message:'Unable to load locations')}}
 useEffect(()=>{void refresh()},[])
 const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.description??''}`.toLowerCase().includes(query.toLowerCase())),[items,query]); const pageSize=10,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),paged=filtered.slice((page-1)*pageSize,page*pageSize)
 useEffect(()=>setPage(1),[query])
 const edit=(x:ScavengerLocation)=>{setEditing(x);setForm({name:x.name,description:x.description??'',icon:x.icon??'',sortOrder:x.sortOrder,isActive:x.isActive,image:null});setOpen(true)}
 const create=()=>{setEditing(null);setForm(empty);setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const fd=new FormData();fd.set('name',form.name);fd.set('description',form.description);fd.set('icon',form.icon);fd.set('sortOrder',String(form.sortOrder));fd.set('isActive',String(form.isActive));if(form.image)fd.set('image',form.image);if(editing)await adminUpdateScavengerLocation(editing.id,fd);else await adminCreateScavengerLocation(fd);setOpen(false);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to save location')}finally{setBusy(false)}}
 async function toggle(x:ScavengerLocation){try{await adminSetScavengerLocationStatus(x.id,!x.isActive);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to update status')}}
 async function remove(){if(!del)return;setBusy(true);try{await adminDeleteScavengerLocation(del.id);setDel(null);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to delete location')}finally{setBusy(false)}}
 return <div className="admin-scavenger-reference" style={{padding:'28px 32px 42px',maxWidth:1540,margin:'0 auto'}}>
  <AdminHero eyebrow="LOVE IN ACTION" title="Scavenger Hunt" copy="Manage the hiding-place ideas subscribers see in the separate Scavenger Hunt experience." action={<button className="hs-btn" onClick={create}>+ Add Location</button>}/>
  <div className="hs-stats four"><StatCard label="TOTAL LOCATIONS" value={items.length} note="All scavenger suggestions."/><StatCard label="ACTIVE" value={items.filter(x=>x.isActive).length} note="Visible to subscribers."/><StatCard label="INACTIVE" value={items.filter(x=>!x.isActive).length} note="Hidden from the public page."/><StatCard accent label="NEXT ORDER" value={(Math.max(0,...items.map(x=>x.sortOrder))+10)} note="Suggested sort order for a new item."/></div>
  <Panel><div className="hs-panel-head"><div><span className="hs-eyebrow">SCAVENGER LOCATIONS</span><h2>Where to Leave It</h2><p>Add, edit, reorder, activate or remove the location ideas used on the Scavenger Hunt page.</p></div></div>
   <div className="hs-filter"><div className="hs-search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search locations..."/></div></div>{error&&<div className="hs-error">{error}</div>}
   <div className="hs-table"><div className="hs-tr head" style={{gridTemplateColumns:'90px 1.3fr 2fr 100px 120px 120px'}}><span>IMAGE</span><span>LOCATION</span><span>DESCRIPTION</span><span>ORDER</span><span>STATUS</span><span>ACTIONS</span></div>{paged.map(x=><div className="hs-tr" key={x.id} style={{gridTemplateColumns:'90px 1.3fr 2fr 100px 120px 120px'}}><span>{x.imageUrl?<img src={x.imageUrl} alt="" style={{width:64,height:48,objectFit:'cover',borderRadius:10}}/>:<span style={{display:'grid',placeItems:'center',width:64,height:48,borderRadius:10,background:'#f4eee5',fontSize:20}}>♡</span>}</span><span><b>{x.name}</b><small>{x.icon||'No icon label'}</small></span><span>{x.description||'—'}</span><span>{x.sortOrder}</span><span><button type="button" onClick={()=>void toggle(x)} style={{border:0,borderRadius:999,padding:'7px 12px',fontWeight:700,color:'#fff',background:x.isActive?'#2f7659':'#c65353'}}>{x.isActive?'Active':'Inactive'}</button></span><span className="hs-row-actions"><button onClick={()=>edit(x)} title="Edit"><Pencil/></button><button className="danger" onClick={()=>setDel(x)} title="Delete"><Trash/></button></span></div>)}{!filtered.length&&<div className="hs-empty">No scavenger locations found.</div>}</div>
   <AdminPagination page={page} pageSize={pageSize} total={filtered.length} totalPages={totalPages} onPageChange={setPage}/>
  </Panel>
  {open&&<div className="hs-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setOpen(false)}}><section className="hs-modal"><div className="hs-modal-head"><div><span className="hs-eyebrow">{editing?'EDIT LOCATION':'NEW LOCATION'}</span><h2>{editing?'Edit Scavenger Location':'Add Scavenger Location'}</h2><p>This controls what subscribers see on the Scavenger Hunt page.</p></div><button className="hs-modal-close" onClick={()=>setOpen(false)}>×</button></div><form className="hs-taxonomy-form hs-modal-form" onSubmit={save}><label>Location Name<input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/></label><label>Description<textarea rows={3} value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))}/></label><label>Icon Label (optional)<input value={form.icon} onChange={e=>setForm(v=>({...v,icon:e.target.value}))} placeholder="e.g. coffee"/></label><label>Display Order<input type="number" min="0" value={form.sortOrder} onChange={e=>setForm(v=>({...v,sortOrder:Number(e.target.value)}))}/></label><label>Location Image (optional)<input type="file" accept="image/*" onChange={e=>setForm(v=>({...v,image:e.target.files?.[0]??null}))}/></label><label className="hs-taxonomy-check"><input type="checkbox" checked={form.isActive} onChange={e=>setForm(v=>({...v,isActive:e.target.checked}))}/><span>Active and visible to subscribers</span></label><div className="hs-form-actions"><button type="button" className="hs-outline" onClick={()=>setOpen(false)}>Cancel</button><button className="hs-btn" disabled={busy}>{busy?'Saving…':'Save Location'}</button></div></form></section></div>}
  {del&&<div className="hs-modal-backdrop"><section className="hs-modal hs-confirm-modal"><div className="hs-confirm-icon"><Trash/></div><span className="hs-eyebrow">DELETE LOCATION</span><h2>Delete “{del.name}”?</h2><p>It will immediately disappear from the subscriber Scavenger Hunt page.</p><div className="hs-form-actions hs-confirm-actions"><button className="hs-outline" onClick={()=>setDel(null)}>Cancel</button><button className="hs-danger-btn" disabled={busy} onClick={()=>void remove()}>{busy?'Deleting…':'Delete Location'}</button></div></section></div>}
 </div>
}
