import { useEffect, useMemo, useState } from 'react'
import { adminGetSubscriptions, type AdminPagination, type AdminSubscriptionsResponse } from '../../services/api'

const pg={page:1,pageSize:10,total:0,totalPages:1}
const initial:AdminSubscriptionsResponse={summary:{totalSubscribers:0,monthlyRevenue:0,activeSubscriptions:0,monthlyPrice:8.99},subscribers:[],transactions:[],failedPayments:[],pagination:pg,transactionPagination:{...pg}}
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
const date=(v:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(v))
const normalize=(v:string)=>v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const tone=(v:string)=>v==='SUCCESS'||v==='ACTIVE'?'good':v==='FAILED'||v==='PAYMENT_ISSUE'||v==='PAST_DUE'?'bad':'neutral'

function Pill({value}:{value:string}){
 const t=tone(value)
 const cls=t==='good'?'border-[rgba(23,57,47,0.18)] bg-[rgba(23,57,47,0.1)] text-[#17392f]':t==='bad'?'border-[rgba(125,74,74,0.18)] bg-[rgba(125,74,74,0.11)] text-[#7a4a4a]':'border-[rgba(119,109,98,0.14)] bg-[rgba(119,109,98,0.08)] text-[#7d7165]'
 return <span className={`inline-flex min-h-[34px] items-center whitespace-nowrap rounded-full border px-3 text-[0.84rem] font-bold leading-none ${cls}`}>{normalize(value)}</span>
}

function Pagination({meta,onChange,label='Pagination'}:{meta:AdminPagination,onChange:(page:number)=>void,label?:string}){
 const {page,totalPages,total,pageSize}=meta
 if(total===0)return null
 const start=(page-1)*pageSize+1,end=Math.min(total,page*pageSize)
 const pages=useMemo(()=>{
   const arr:number[]=[]; const from=Math.max(1,page-2),to=Math.min(totalPages,from+4)
   for(let i=Math.max(1,to-4);i<=to;i++)arr.push(i)
   return arr
 },[page,totalPages])
 return <footer className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-[rgba(57,47,39,0.12)] pt-4">
   <div className="text-[0.9rem] text-[#776d62]">Showing <b className="text-[#2f2a25]">{start}-{end}</b> of <b className="text-[#2f2a25]">{total}</b></div>
   <nav aria-label={label} className="flex flex-wrap items-center justify-center gap-2">
    <button type="button" disabled={page<=1} onClick={()=>onChange(page-1)} className="min-h-10 rounded-full border border-[rgba(57,47,39,0.12)] bg-[#faf7f2] px-4 text-sm text-[#2f2a25] transition hover:bg-[#f4eee5] disabled:cursor-not-allowed disabled:opacity-40">Previous</button>
    {pages.map(p=><button key={p} type="button" aria-current={p===page?'page':undefined} onClick={()=>onChange(p)} className={`h-10 min-w-10 rounded-full border px-3 text-sm transition ${p===page?'border-[#17392f] bg-[#17392f] text-[#f7f4ef] shadow-[0_10px_22px_rgba(23,57,47,0.14)]':'border-[rgba(57,47,39,0.12)] bg-[#faf7f2] text-[#2f2a25] hover:bg-[#f4eee5]'}`}>{p}</button>)}
    <button type="button" disabled={page>=totalPages} onClick={()=>onChange(page+1)} className="min-h-10 rounded-full border border-[rgba(57,47,39,0.12)] bg-[#faf7f2] px-4 text-sm text-[#2f2a25] transition hover:bg-[#f4eee5] disabled:cursor-not-allowed disabled:opacity-40">Next</button>
   </nav>
 </footer>
}

export function SubscriptionsPage(){
 const [data,setData]=useState(initial),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[transactionPage,setTransactionPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{const t=setTimeout(async()=>{setLoading(true);setError('');try{setData(await adminGetSubscriptions({search,status,page,pageSize:10,transactionPage,transactionPageSize:10}))}catch(e){setError(e instanceof Error?e.message:'Unable to load subscriptions')}finally{setLoading(false)}},180);return()=>clearTimeout(t)},[search,status,page,transactionPage])
 useEffect(()=>setPage(1),[search,status])
 return <main className="min-w-0 px-8 py-7 pb-[42px] max-[760px]:px-[18px]">
  <div className="mx-auto max-w-[1540px]">
   <header className="mb-6 flex items-start justify-between gap-6 rounded-[28px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-[30px] shadow-[0_18px_40px_rgba(47,37,28,0.06)] max-[720px]:p-5">
    <div className="min-w-0 flex-1"><span className="mb-2 inline-block text-[0.74rem] uppercase tracking-[0.18em] text-[#776d62]">Admin section</span><h1 className="m-0 font-serif text-5xl font-semibold leading-none tracking-[-0.03em] md:text-6xl">Subscriptions &amp; Payments</h1><p className="mt-2.5 max-w-[720px] text-base text-[#776d62]">A calm operational view of subscriber records, payment activity, and overall subscription health for the single monthly plan.</p></div>
   </header>

   <section className="mb-[22px] grid grid-cols-4 gap-4 max-[1360px]:grid-cols-2 max-[720px]:grid-cols-1" aria-label="Subscription summary">
    <article className="min-w-0 rounded-[22px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-5 shadow-[0_10px_22px_rgba(47,37,28,0.04)]"><span className="mb-3 inline-flex text-[0.74rem] uppercase tracking-[0.14em] text-[#776d62]">Total Subscribers</span><h2 className="m-0 text-[2rem] font-bold leading-none tracking-[-0.04em] text-[#17392f]">{data.summary.totalSubscribers}</h2><p className="m-0 mt-2.5 text-[0.92rem] text-[#776d62]">All records across active, cancelled, and payment issue accounts.</p></article>
    <article className="min-w-0 rounded-[22px] border border-[rgba(23,57,47,0.35)] bg-[linear-gradient(160deg,rgba(23,57,47,0.98),rgba(39,74,63,0.94))] p-5 text-[#f7f4ef] shadow-[0_10px_22px_rgba(47,37,28,0.04)]"><span className="mb-3 inline-flex text-[0.74rem] uppercase tracking-[0.14em]">Monthly Revenue</span><h2 className="m-0 text-[2rem] font-bold leading-none tracking-[-0.04em]">{money(data.summary.monthlyRevenue)}</h2><p className="m-0 mt-2.5 text-[0.92rem] text-[rgba(247,244,239,0.76)]">Successful subscription payments recorded this month.</p></article>
    <article className="min-w-0 rounded-[22px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-5 shadow-[0_10px_22px_rgba(47,37,28,0.04)]"><span className="mb-3 inline-flex text-[0.74rem] uppercase tracking-[0.14em] text-[#776d62]">Active Subscriptions</span><h2 className="m-0 text-[2rem] font-bold leading-none tracking-[-0.04em] text-[#17392f]">{data.summary.activeSubscriptions}</h2><p className="m-0 mt-2.5 text-[0.92rem] text-[#776d62]">Steady monthly access across the full card library.</p></article>
    <article className="min-w-0 rounded-[22px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-5 shadow-[0_10px_22px_rgba(47,37,28,0.04)]"><span className="mb-3 inline-flex text-[0.74rem] uppercase tracking-[0.14em] text-[#776d62]">Monthly Price</span><h2 className="m-0 text-[2rem] font-bold leading-none tracking-[-0.04em] text-[#17392f]">{money(data.summary.monthlyPrice)}</h2><p className="m-0 mt-2.5 text-[0.92rem] text-[#776d62]">Configured monthly subscription price from Stripe.</p></article>
   </section>

   <section className="grid grid-cols-12 gap-[18px]">
    <section className="col-span-12 rounded-[28px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-6 shadow-[0_18px_40px_rgba(47,37,28,0.06)] max-[720px]:p-[18px]">
     <div className="mb-[18px]"><span className="mb-2 inline-block text-[0.74rem] uppercase tracking-[0.18em] text-[#776d62]">Subscriber records</span><h2 className="m-0 font-serif text-[2rem] font-semibold leading-[0.98] tracking-[-0.02em]">Subscriber List</h2><p className="mt-2 max-w-[700px] text-[0.95rem] text-[#776d62]">A premium operational view of member records, subscription status, billing rhythm, and recent payment standing.</p></div>
     <div className="mb-5 flex flex-wrap gap-4">
      <label className="min-w-72 flex-1 rounded-2xl border border-[#e4dbcf] bg-[#f9f5ef] p-4"><span className="mb-[9px] block text-[0.74rem] uppercase tracking-[0.16em] text-[#776d62]">Search subscribers</span><span className="flex min-h-11 items-center gap-2 rounded-[14px] border border-[rgba(57,47,39,0.12)] bg-[rgba(255,255,255,0.58)] px-3.5 focus-within:ring-4 focus-within:ring-[rgba(23,57,47,0.06)]">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name or email" className="min-w-0 flex-1 border-0 bg-transparent p-0 text-[#2f2a25] outline-none"/></span></label>
      <label className="min-w-72 flex-1 rounded-2xl border border-[#e4dbcf] bg-[#f9f5ef] p-4"><span className="mb-[9px] block text-[0.74rem] uppercase tracking-[0.16em] text-[#776d62]">Filter by status</span><select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 w-full rounded-[14px] border border-[rgba(57,47,39,0.12)] bg-[rgba(255,255,255,0.58)] px-3.5 text-[#2f2a25] outline-none"><option value="">All subscription statuses</option><option value="ACTIVE">Active</option><option value="CANCELLED">Cancelled</option><option value="PAYMENT_ISSUE">Payment Issue</option><option value="INCOMPLETE">Incomplete</option><option value="PAST_DUE">Past Due</option></select></label>
     </div>
     {error&&<div className="mb-4 rounded-[14px] bg-[#f8e8e5] p-4 text-[#8d3c35]">{error}</div>}
     <div className="overflow-x-auto max-[720px]:hidden"><table className="w-full min-w-[900px] border-collapse"><thead><tr>{['User Name','Email','Plan','Subscription Status','Next Billing Date','Payment Status','Actions'].map(h=><th key={h} className="pb-3.5 text-left text-[0.74rem] font-bold uppercase tracking-[0.16em] text-[#776d62]">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="border-t border-[rgba(57,47,39,0.12)] py-10 text-center text-[#776d62]">Loading subscriber records…</td></tr>:data.subscribers.length===0?<tr><td colSpan={7} className="border-t border-[rgba(57,47,39,0.12)] py-10 text-center text-[#776d62]">No subscriber records found.</td></tr>:data.subscribers.map(s=><tr key={s.id}><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top text-[0.95rem]"><b className="block">{s.fullName}</b><span className="mt-[3px] block text-[0.86rem] text-[#776d62]">Subscriber since {date(s.createdAt)}</span></td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top text-[0.95rem]">{s.email}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top text-[0.95rem]">{s.planName}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top"><Pill value={s.status}/></td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top text-[0.95rem]">{s.currentPeriodEnd?date(s.currentPeriodEnd):'Not available'}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top"><Pill value={s.paymentStatus}/></td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] align-top"><button disabled={!s.stripeDashboardUrl} onClick={()=>s.stripeDashboardUrl&&window.open(s.stripeDashboardUrl,'_blank','noopener,noreferrer')} className="inline-flex min-h-[38px] items-center justify-center rounded-full border border-[rgba(57,47,39,0.12)] bg-[#f9f5ef] px-3.5 text-[0.87rem] font-bold text-[#17392f] transition hover:-translate-y-px disabled:opacity-40">View Details</button></td></tr>)}</tbody></table></div>
     <div className="hidden gap-3 max-[720px]:grid">{data.subscribers.map(s=><article key={s.id} className="rounded-[20px] border border-[rgba(57,47,39,0.12)] bg-[#f9f5ef] p-4"><div className="mb-3"><strong>{s.fullName}</strong><span className="mt-[3px] block text-[0.86rem] text-[#776d62]">Subscriber since {date(s.createdAt)}</span></div><div className="grid grid-cols-2 gap-3 max-[520px]:grid-cols-1"><div><small className="block uppercase text-[#776d62]">Email</small>{s.email}</div><div><small className="block uppercase text-[#776d62]">Plan</small>{s.planName}</div><div><small className="block uppercase text-[#776d62]">Status</small><Pill value={s.status}/></div><div><small className="block uppercase text-[#776d62]">Next Billing</small>{s.currentPeriodEnd?date(s.currentPeriodEnd):'Not available'}</div><div><small className="block uppercase text-[#776d62]">Payment</small><Pill value={s.paymentStatus}/></div><div>{s.stripeDashboardUrl&&<button onClick={()=>window.open(s.stripeDashboardUrl!,'_blank','noopener,noreferrer')} className="rounded-full border border-[rgba(57,47,39,0.12)] px-3.5 py-2 font-bold text-[#17392f]">View Details</button>}</div></div></article>)}</div>
     <Pagination meta={data.pagination} onChange={setPage}/>
    </section>

    <section className="col-span-12 flex flex-col justify-between rounded-[28px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-6 shadow-[0_18px_40px_rgba(47,37,28,0.06)] max-[720px]:p-[18px] xl:col-span-7">
     <div><div className="mb-[18px]"><span className="mb-2 inline-block text-[0.74rem] uppercase tracking-[0.18em] text-[#776d62]">Payment activity</span><h2 className="m-0 font-serif text-[2rem] font-semibold leading-[0.98] tracking-[-0.02em]">Recent Transactions</h2><p className="mt-2 text-[0.95rem] text-[#776d62]">A clean, recent view of subscription payment activity with quiet visibility into successful and failed charges.</p></div>
     <div className="overflow-x-auto max-[720px]:hidden"><table className="w-full min-w-[760px] border-collapse"><thead><tr>{['Transaction ID','User Name','Date','Amount','Status'].map(h=><th key={h} className="pb-3.5 text-left text-[0.74rem] font-bold uppercase tracking-[0.16em] text-[#776d62]">{h}</th>)}</tr></thead><tbody>{data.transactions.map(t=><tr key={t.id}><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top text-[0.95rem]"><b className="block">{t.providerTransactionId}</b><span className="mt-[3px] block text-[0.86rem] text-[#776d62]">{t.description}</span></td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top">{t.fullName}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top">{date(t.date)}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] pr-5 align-top">{money(t.amount)}</td><td className="border-t border-[rgba(57,47,39,0.12)] py-[15px] align-top"><Pill value={t.status}/></td></tr>)}</tbody></table></div>
     <div className="hidden gap-3 max-[720px]:grid">{data.transactions.map(t=><article key={t.id} className="rounded-[20px] border border-[rgba(57,47,39,0.12)] bg-[#f9f5ef] p-4"><b className="block break-all">{t.providerTransactionId}</b><span className="text-[0.86rem] text-[#776d62]">{t.description}</span><div className="mt-3 grid grid-cols-2 gap-3 max-[520px]:grid-cols-1"><div>{t.fullName}</div><div>{date(t.date)}</div><div>{money(t.amount)}</div><div><Pill value={t.status}/></div></div></article>)}</div></div>
     <Pagination meta={data.transactionPagination} onChange={setTransactionPage} label="Transactions pagination"/>
    </section>

    <section className="col-span-12 flex flex-col justify-between rounded-[28px] border border-[rgba(57,47,39,0.12)] bg-[#fcfaf7] p-6 shadow-[0_18px_40px_rgba(47,37,28,0.06)] max-[720px]:p-[18px] xl:col-span-5">
     <div><div className="mb-[18px]"><span className="mb-2 inline-block text-[0.74rem] uppercase tracking-[0.18em] text-[#776d62]">Attention needed</span><h2 className="m-0 font-serif text-[2rem] font-semibold leading-[0.98] tracking-[-0.02em]">Failed Payments</h2><p className="mt-2 text-[0.95rem] text-[#776d62]">A focused list of subscriber accounts with recent payment issues that may need closer review.</p></div><div className="grid gap-3 mt-6">{data.failedPayments.length===0?<div className="rounded-[24px] border border-dashed border-[rgba(57,47,39,0.18)] bg-[linear-gradient(180deg,rgba(249,245,239,0.84),rgba(252,250,247,0.96))] p-[30px] text-center text-[0.96rem] text-[#776d62]">No failed payments found.</div>:data.failedPayments.map(f=><div key={f.id} className="rounded-[20px] border border-[rgba(125,74,74,0.15)] bg-[rgba(125,74,74,0.05)] p-4"><b className="block">{f.fullName}</b><span className="text-sm text-[#776d62]">{f.email}</span><div className="mt-2 flex items-center justify-between gap-3"><span>{money(f.amount)} · {date(f.date)}</span><Pill value={f.status}/></div></div>)}</div></div>
    </section>
   </section>
  </div>
 </main>
}
