import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { adminGetUsers, adminSetUserStatus, type AdminUser, type AdminUsersResponse } from '../../services/api'

const initial: AdminUsersResponse = { summary:{totalUsers:0,activeSubscribers:0,freeUsers:0,blockedUsers:0}, users:[], pagination:{page:1,pageSize:10,total:0,totalPages:1} }
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(p=>p[0]).join('').toUpperCase() || 'U'}
function formatDate(value:string){return new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(value))}
function badgeClass(value:string){return ['ACTIVE'].includes(value)?'active':value==='ADMIN'?'admin':value==='BLOCKED'?'blocked':'muted'}
const EyeIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></svg>
const BanIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M4.929 4.929 19.07 19.071"/></svg>
const CheckIcon=()=> <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m9 12 2 2 4-4"/><circle cx="12" cy="12" r="10"/></svg>

export function UsersPage(){
  const [data,setData]=useState(initial),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [search,setSearch]=useState(''),[role,setRole]=useState(''),[status,setStatus]=useState(''),[subscription,setSubscription]=useState(''),[page,setPage]=useState(1)
  const [confirmUser,setConfirmUser]=useState<AdminUser|null>(null),[updating,setUpdating]=useState(false)
  async function load(){setLoading(true);setError('');try{setData(await adminGetUsers({search,role,status,subscription,page,pageSize:10}))}catch(e){setError(e instanceof Error?e.message:'Unable to load users')}finally{setLoading(false)}}
  useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[search,role,status,subscription,page])
  useEffect(()=>setPage(1),[search,role,status,subscription])
  async function confirmStatus(){if(!confirmUser)return;setUpdating(true);try{await adminSetUserStatus(confirmUser.id,confirmUser.status==='BLOCKED'?'ACTIVE':'BLOCKED');setConfirmUser(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update user')}finally{setUpdating(false)}}
  const reset=()=>{setSearch('');setRole('');setStatus('');setSubscription('');setPage(1)}
  const start=data.pagination.total===0?0:(data.pagination.page-1)*data.pagination.pageSize+1
  const end=Math.min(data.pagination.page*data.pagination.pageSize,data.pagination.total)
  const pages=Array.from({length:data.pagination.totalPages},(_,i)=>i+1).filter(p=>p===1||p===data.pagination.totalPages||Math.abs(p-page)<=1)
  const userRows=data.users.map(user=><div className="au-row" key={user.id}>
    <div className="au-person"><i>{initials(user.fullName)}</i><div><b>{user.fullName}</b><small>Joined {formatDate(user.joinedAt)}</small></div></div>
    <div className="au-email">{user.email}</div><div><span className={`au-badge ${badgeClass(user.role)}`}>{user.role}</span></div><div><span className={`au-badge ${badgeClass(user.status)}`}>{user.status}</span></div><div><span className={`au-badge ${badgeClass(user.subscriptionStatus)}`}>{user.subscriptionStatus}</span></div><div>{formatDate(user.joinedAt)}</div>
    <div className="au-actions"><Link to={`/admin/users/${user.id}`} aria-label="View user" title="View user"><EyeIcon/></Link><button type="button" disabled={user.role==='ADMIN'} onClick={()=>setConfirmUser(user)} title={user.role==='ADMIN'?'Admin account cannot be blocked':user.status==='BLOCKED'?'Unblock user':'Block user'} aria-label={user.role==='ADMIN'?'Admin account cannot be blocked':user.status==='BLOCKED'?'Unblock user':'Block user'}>{user.status==='BLOCKED'?<CheckIcon/>:<BanIcon/>}</button></div>
  </div>)
  return <main className="admin-users-reference">
    <header className="au-hero"><span className="au-kicker">Admin panel</span><h1>Users</h1><p>View user accounts, roles, subscription access, and account status.</p></header>
    <section className="au-panel"><div className="au-heading"><span className="au-kicker">Accounts</span><h2>Users Management</h2><p>Server-backed account rows for reviewing roles, status, subscription access, and admin actions.</p></div>
      <div className="au-stats"><article><span>Total Users</span><strong>{data.summary.totalUsers}</strong><p>All registered accounts.</p></article><article><span>Active Subscribers</span><strong>{data.summary.activeSubscribers}</strong><p>Users with active subscription access.</p></article><article><span>Free Users</span><strong>{data.summary.freeUsers}</strong><p>Users without active paid access.</p></article><article className="accent"><span>Blocked Users</span><strong>{data.summary.blockedUsers}</strong><p>Accounts currently blocked.</p></article></div>
      <div className="au-filters"><label className="au-search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search users..." type="search"/></label><select value={role} onChange={e=>setRole(e.target.value)}><option value="">User Role</option><option value="USER">User</option><option value="ADMIN">Admin</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">User Status</option><option value="ACTIVE">Active</option><option value="BLOCKED">Blocked</option></select><select value={subscription} onChange={e=>setSubscription(e.target.value)}><option value="">Subscription Status</option><option value="INCOMPLETE">Incomplete</option><option value="ACTIVE">Active</option><option value="PAST_DUE">Past Due</option><option value="PAYMENT_ISSUE">Payment Issue</option><option value="CANCELLED">Cancelled</option><option value="NONE">None</option></select><button type="button" onClick={reset}>Reset Filters</button></div>
      {error&&<div className="hs-error">{error}</div>}
      <div className="au-table-wrap"><div className="au-table"><div className="au-row head"><div>User</div><div>Email</div><div>Role</div><div>Status</div><div>Subscription</div><div>Joined</div><div>Actions</div></div>{loading?<div className="au-empty">Loading users…</div>:data.users.length===0?<div className="au-empty">No users found</div>:userRows}<footer className="au-pagination"><div>Showing <b>{start}-{end}</b> of <b>{data.pagination.total}</b></div><nav><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button>{pages.map((p,i)=><span key={p}>{i>0&&pages[i-1]!==p-1?<i>…</i>:null}<button className={p===page?'current':''} onClick={()=>setPage(p)}>{p}</button></span>)}<button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav></footer></div></div>
      <div className="au-mobile">{loading?<div className="au-empty">Loading users…</div>:data.users.map(user=><article key={user.id}><div className="au-person"><i>{initials(user.fullName)}</i><div><b>{user.fullName}</b><small>Joined {formatDate(user.joinedAt)}</small></div></div><dl><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Joined</dt><dd>{formatDate(user.joinedAt)}</dd></div><div><dt>Role</dt><dd><span className={`au-badge ${badgeClass(user.role)}`}>{user.role}</span></dd></div><div><dt>Status</dt><dd><span className={`au-badge ${badgeClass(user.status)}`}>{user.status}</span></dd></div><div className="wide"><dt>Subscription</dt><dd><span className={`au-badge ${badgeClass(user.subscriptionStatus)}`}>{user.subscriptionStatus}</span></dd></div></dl><div className="au-actions"><Link to={`/admin/users/${user.id}`}><EyeIcon/></Link><button disabled={user.role==='ADMIN'} onClick={()=>setConfirmUser(user)}>{user.status==='BLOCKED'?<CheckIcon/>:<BanIcon/>}</button></div></article>)}<footer className="au-pagination"><div>Showing <b>{start}-{end}</b> of <b>{data.pagination.total}</b></div><nav><button disabled={page<=1} onClick={()=>setPage(page-1)}>Previous</button><button className="current">{page}</button><button disabled={page>=data.pagination.totalPages} onClick={()=>setPage(page+1)}>Next</button></nav></footer></div>
    </section>
    {confirmUser&&<div className="au-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget&&!updating)setConfirmUser(null)}}><section className="au-modal" role="dialog" aria-modal="true" aria-labelledby="user-status-title"><div className={`au-modal-icon ${confirmUser.status==='BLOCKED'?'restore':'danger'}`}>{confirmUser.status==='BLOCKED'?<CheckIcon/>:<BanIcon/>}</div><span className="au-kicker">Account status</span><h2 id="user-status-title">{confirmUser.status==='BLOCKED'?'Unblock this user?':'Block this user?'}</h2><p>{confirmUser.status==='BLOCKED'?<>Restore access for <b>{confirmUser.fullName}</b> ({confirmUser.email})?</>:<>Block <b>{confirmUser.fullName}</b> ({confirmUser.email}) from accessing their account?</>}</p>{confirmUser.status!=='BLOCKED'&&<div className="au-warning">The user will be unable to access protected account features until an administrator unblocks the account.</div>}<div className="au-modal-actions"><button type="button" className="cancel" disabled={updating} onClick={()=>setConfirmUser(null)}>Cancel</button><button type="button" className={confirmUser.status==='BLOCKED'?'restore':'danger'} disabled={updating} onClick={confirmStatus}>{updating?'Updating…':confirmUser.status==='BLOCKED'?'Yes, Unblock User':'Yes, Block User'}</button></div></section></div>}
  </main>
}
