import {useEffect,useState} from 'react'; import {Link} from 'react-router-dom'; import {cancelMyOrder,getMyOrders,UserOrder} from '../../services/api'
const money=(n:number|null)=>n==null?'Pending':`$${n.toFixed(2)}`; const short=(s:string)=>s.length>9?s.slice(0,8)+'…':s
const statusText:Record<string,string>={PLACED:'We are reviewing shipping and will email you when the final price is ready.',QUOTED:'Your shipping quote is ready for review.',IN_PROGRESS:'Your order is being prepared.',SHIPPED:'Your order is on the way.',DELIVERED:'Your order has been delivered.',CANCELLED:'This order was cancelled.'}
export function UserOrdersPage(){const [data,setData]=useState<any>(null),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true)
 const load=()=>{setLoading(true);getMyOrders({search,status}).then(setData).finally(()=>setLoading(false))}; useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[search,status])
 async function cancel(o:UserOrder){if(!confirm('Cancel this order?'))return; try{await cancelMyOrder(o.id);load()}catch(e:any){alert(e.message)}}
 return <main className="customer-orders"><section className="orders-hero"><div><span>ORDER TRACKING</span><h1>Your Card Orders</h1><p>Follow each poetry card order from request to delivery, with a clear<br/>view of shipping fees, status, and where things stand.</p></div><div className="order-stats"><Stat n={data?.summary.activeOrders??0} t="Active orders"/><Stat n={data?.summary.totalCardsOrdered??0} t="Total cards ordered"/><Stat n={data?.summary.deliveredTotal??0} t="Delivered total"/></div></section>
 <section className="orders-filter"><div>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by order number, recipient, or card title"/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Order Status</option>{['PLACED','QUOTED','IN_PROGRESS','SHIPPED','DELIVERED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></section>
 {loading?<div className="orders-empty">Loading orders…</div>:!data?.orders.length?<div className="orders-empty"><h2>No card orders yet</h2><p>Your physical card orders will appear here.</p></div>:data.orders.map((o:UserOrder)=><article className="customer-order-card" key={o.id}><div className="order-art">{o.previewUrl?<img src={o.previewUrl}/>:<><strong>{o.cardTitle}</strong><small>You arrived like<br/>evening light, resting…</small></>}</div><div className="order-main"><div className="order-title-row"><div><h2>{o.cardTitle}</h2><p><b>{short(o.orderNumber)}</b> ▣ &nbsp; Placed {new Date(o.placedAt).toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'})}</p></div><em className={'order-status '+o.status.toLowerCase()}>● {o.status.replace('_',' ')}</em></div><div className="current-status"><b>Current status:</b> {statusText[o.status]||o.status}</div><div className="order-facts"><div><label>RECIPIENT</label><b>{o.shippingName||'Not provided'}</b></div><div><label>QUANTITY</label><b>{o.quantity} card{o.quantity===1?'':'s'}</b></div><div><label>SHIPPING</label><b>{o.shippingFee==null?'Awaiting quote':money(o.shippingFee)}</b></div></div><div className="order-actions"><Link to={`/orders/${o.id}`}>View Order Details</Link>{['PLACED','QUOTED'].includes(o.status)&&<button onClick={()=>cancel(o)}>⊗ &nbsp; Cancel Order</button>}</div></div><aside><div><label>SHIPPING ADDRESS</label><p>{o.shippingAddress||'Not provided'}</p></div><div><label>ORDER SUMMARY</label><p>Cards subtotal <b>{o.totalAmount!=null&&o.shippingFee!=null?money(o.totalAmount-o.shippingFee):'Pending'}</b></p><p>Shipping <b>{money(o.shippingFee)}</b></p><hr/><p>Total <b>{money(o.totalAmount)}</b></p></div></aside></article>)}</main>}
function Stat({n,t}:{n:number,t:string}){return <div><strong>{String(n).padStart(2,'0')}</strong><span>{t}</span></div>}
