import { Link, useParams } from 'react-router-dom'
import { CategorySection } from '../../components/CategorySection'
import { categories } from '../../data/cards'
import { EmptyState, MiniCardGrid, PageHeader, Panel, Stat } from '../../components/app/PagePrimitives'

export function LandingSecondaryPage() { return <div className="content-page"><PageHeader eyebrow="Discover" title="Poetry made personal." copy="Browse meaningful cards, save favourites, and add your own message."/><MiniCardGrid/><Panel title="Browse by feeling"><div className="chip-row">{['Love','Birthday','Anniversary','Gratitude','Friendship','Family'].map(x=><Link to={`/category/${x.toLowerCase()}`} className="chip" key={x}>{x}</Link>)}</div></Panel></div> }
export function SearchPage() { return <div className="content-page"><PageHeader eyebrow="Library" title="Find the right words." copy="Search poems by occasion, feeling, or a phrase you remember."/><Panel><div className="search-bar"><input placeholder="Search poetry cards"/><button className="button">Search</button></div><div className="filter-row">{['All','Love','Birthday','Anniversary','Family'].map(x=><button key={x}>{x}</button>)}</div></Panel><MiniCardGrid/></div> }
export function CategoriesPage() { return <div className="content-page"><PageHeader eyebrow="Collections" title="Browse every category." copy="Poetry organised around moments that matter."/><div className="category-tile-grid">{categories.map(c=><Link to={`/category/${c.name.toLowerCase().replaceAll(' ','-')}`} className="category-tile" key={c.name}><span>Category</span><h2>{c.name}</h2><p>{c.subtitle}</p></Link>)}</div></div> }
export function CategoryPage() { const {slug='love'}=useParams(); const name=slug.split('-').map(s=>s[0]?.toUpperCase()+s.slice(1)).join(' '); return <div className="content-page"><PageHeader eyebrow="Category" title={name} copy="Choose a card, open it, and make the message yours."/><MiniCardGrid/><MiniCardGrid/></div> }
export function SignUpPage() { return <AuthPage title="Create your account" action="Create Account" alternate="Already have an account?" alternateTo="/sign-in"/> }
export function SignInPage() { return <AuthPage title="Welcome back" action="Sign In" alternate="New to Verse & Feeling?" alternateTo="/sign-up"/> }
export function ChangePasswordPage() { return <AuthPage title="Change password" action="Update Password" alternate="Return to profile" alternateTo="/profile"/> }
export function ResetPasswordPage() { return <AuthPage title="Reset your password" action="Send Reset Link" alternate="Remembered your password?" alternateTo="/sign-in" emailOnly/> }
function AuthPage({title,action,alternate,alternateTo,emailOnly=false}:{title:string;action:string;alternate:string;alternateTo:string;emailOnly?:boolean}) { return <div className="auth-page"><form className="auth-card"><p className="eyebrow">Account</p><h1>{title}</h1><label>Email<input type="email" placeholder="you@example.com"/></label>{!emailOnly&&<label>Password<input type="password" placeholder="••••••••"/></label>}<button className="button" type="button">{action}</button><p>{alternate} <Link to={alternateTo}>Continue</Link></p></form></div> }
export function DashboardPage() { return <div className="content-page"><PageHeader eyebrow="Your account" title="Good morning." copy="Continue exploring your saved cards and recent activity."/><div className="stat-grid"><Stat label="Saved cards" value="24"/><Stat label="Downloads" value="8"/><Stat label="Subscription" value="Active"/></div><Panel title="Recently viewed"><MiniCardGrid/></Panel></div> }
export function CardFrontPage(){return <CardDetail side="Front" subscribed/>}
export function CardBackPage(){return <CardDetail side="Back" subscribed/>}
export function CardFrontLockedPage(){return <CardDetail side="Front"/>}
export function CardBackLockedPage(){return <CardDetail side="Back"/>}
function CardDetail({side,subscribed=false}:{side:string;subscribed?:boolean}){return <div className="content-page"><PageHeader eyebrow="Card detail" title={`${side} preview`} copy={subscribed?'Personalise and download this card.':'Subscribe to unlock downloads and full personalisation.'}/><div className="card-detail-layout"><article className="large-poem theme-forest inverse"><span className="pill">Love</span><div><h2>Still Choosing You</h2><p>Every day, I choose you all over again.</p></div><small>Verse & Feeling™</small></article><Panel title={subscribed?'Make it yours':'Unlock this card'}>{subscribed?<><label className="field">Your message<textarea defaultValue="With all my love, today and always."/></label><div className="button-row"><button className="button">Save</button><button className="secondary-button">Download</button></div></>:<EmptyState title="Members-only card" copy="Start your subscription for unlimited viewing and downloads." to="/sign-up" label="Start Access"/>}</Panel></div></div>}
export function OrderCardPage(){return <div className="content-page"><PageHeader eyebrow="Printed card" title="Order your card." copy="Choose paper, quantity, delivery address, and a handwritten message."/><div className="two-column"><Panel title="Order details"><FormFields/></Panel><Panel title="Summary"><div className="summary-list"><span>Premium card <strong>$12.00</strong></span><span>Shipping <strong>$4.00</strong></span><span>Total <strong>$16.00</strong></span></div><button className="button full">Continue to payment</button></Panel></div></div>}
function FormFields(){return <div className="form-grid"><label className="field">Full name<input placeholder="Your name"/></label><label className="field">Email<input placeholder="you@example.com"/></label><label className="field full-span">Address<input placeholder="Street address"/></label><label className="field">City<input/></label><label className="field">Postal code<input/></label></div>}
export function LibraryPage(){return <div className="content-page"><PageHeader eyebrow="Saved collection" title="Your library." copy="Cards you saved, downloaded, or recently opened."/><div className="filter-row"><button>Saved</button><button>Downloaded</button><button>Recent</button></div><MiniCardGrid/><MiniCardGrid/></div>}
export function ProfilePage(){return <div className="content-page"><PageHeader eyebrow="Account" title="Profile settings." copy="Manage personal information, subscription, and security."/><div className="two-column"><Panel title="Personal details"><FormFields/><button className="button">Save changes</button></Panel><Panel title="Membership"><Stat label="Current plan" value="Monthly" note="$8.99 / month"/><Link className="secondary-button inline" to="/change-password">Change password</Link></Panel></div></div>}
export function ForumPage(){return <div className="content-page"><PageHeader eyebrow="Community" title="Forum." copy="Share reflections and connect through meaningful words." action={<Link className="button" to="/forum/new">Add Post</Link>}/><PostList/></div>}
export function AddForumPostPage(){return <div className="content-page narrow-page"><PageHeader eyebrow="Community" title="Create a post."/><Panel><label className="field">Title<input placeholder="Post title"/></label><label className="field">Your post<textarea rows={10}/></label><button className="button">Publish post</button></Panel></div>}
export function ForumPostPage(){return <div className="content-page narrow-page"><PageHeader eyebrow="Community post" title="The words we keep returning to." copy="Posted by Maya · 2 hours ago"/><Panel><p className="article-copy">Some poems stay with us because they arrive at exactly the right moment. This thread is a place to share those lines and the memories attached to them.</p></Panel><Panel title="Replies"><PostList compact/></Panel></div>}
function PostList({compact=false}:{compact?:boolean}){return <div className="post-list">{['The words we keep returning to','A card that changed an ordinary day','Poetry for difficult conversations'].slice(0,compact?2:3).map((x,i)=><Link to="/forum/post/1" className="post-row" key={x}><div className="avatar">{['M','A','J'][i]}</div><div><h3>{x}</h3><p>Thoughtful reflections from the Verse & Feeling community.</p></div><span>{12-i*3} replies</span></Link>)}</div>}
export function PoetryRequestsPage(){return <div className="content-page"><PageHeader eyebrow="Custom poetry" title="Your poetry requests." copy="Track submitted requests and their current status." action={<Link className="button" to="/poetry-requests/new">New Request</Link>}/><RequestTable/></div>}
export function AddPoetryRequestPage(){return <div className="content-page narrow-page"><PageHeader eyebrow="Custom poetry" title="Request a poem." copy="Tell us about the moment, person, and feeling."/><Panel><label className="field">Occasion<select><option>Birthday</option><option>Anniversary</option><option>Love</option></select></label><label className="field">Details<textarea rows={9}/></label><button className="button">Submit request</button></Panel></div>}
export function PoetryRequestDetailPage(){return <div className="content-page"><PageHeader eyebrow="Request #PR-1042" title="Anniversary poem." copy="Submitted 28 April · In progress"/><div className="two-column"><Panel title="Request details"><p className="article-copy">A warm anniversary poem for a couple celebrating twenty years together.</p></Panel><Panel title="Status"><div className="timeline"><span className="done">Submitted</span><span className="active">In progress</span><span>Review</span><span>Complete</span></div></Panel></div></div>}
function RequestTable(){return <div className="data-table">{[['PR-1042','Anniversary','In progress'],['PR-1038','Birthday','Completed'],['PR-1029','Love','Review']].map(r=><Link to="/poetry-requests/1" className="data-row" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className="status-pill">{r[2]}</span><span>View →</span></Link>)}</div>}
export function OrdersPage(){return <div className="content-page"><PageHeader eyebrow="Purchases" title="My orders." copy="View printed-card orders and delivery progress."/><div className="data-table">{[['VF-2091','A Year More You','$16.00','Shipped'],['VF-2074','Still Choosing You','$12.00','Delivered']].map(r=><Link to="/orders/1" className="data-row" key={r[0]}>{r.map(x=><span key={x}>{x}</span>)}<span>View →</span></Link>)}</div></div>}
export function OrderDetailPage(){return <div className="content-page"><PageHeader eyebrow="Order VF-2091" title="Order details." copy="Placed 2 May · Estimated arrival 9 May"/><div className="two-column"><Panel title="Delivery"><div className="timeline"><span className="done">Order placed</span><span className="done">Printed</span><span className="active">Shipped</span><span>Delivered</span></div></Panel><Panel title="Summary"><div className="summary-list"><span>Card <strong>$12.00</strong></span><span>Shipping <strong>$4.00</strong></span><span>Total <strong>$16.00</strong></span></div></Panel></div></div>}
