import { useEffect, useRef, useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../auth/AuthContext'
import { getProfile, openBillingPortal, removeProfilePhoto, updatePassword, updateProfile, uploadProfilePhoto, type ProfileData } from '../../services/api'

const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()
const dateText=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'2-digit',year:'numeric'}):'Not scheduled'

export function ProfilePage(){
 const {user,refresh,logout}=useAuth(); const navigate=useNavigate(); const fileRef=useRef<HTMLInputElement>(null)
 const [data,setData]=useState<ProfileData|null>(null),[name,setName]=useState(user?.fullName||''),[phone,setPhone]=useState(user?.phone||'')
 const [message,setMessage]=useState(''),[passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState('')
 useEffect(()=>{getProfile().then(d=>{setData(d);setName(d.user.fullName);setPhone(d.user.phone||'')}).catch(e=>setMessage(e.message))},[])
 async function save(e:FormEvent){e.preventDefault();setMessage('');try{await updateProfile({fullName:name,phone});await refresh();setMessage('Profile saved.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save profile.')}}
 async function photo(file?:File){if(!file)return;setMessage('');try{await uploadProfilePhoto(file);await refresh();setData(await getProfile())}catch(e){setMessage(e instanceof Error?e.message:'Could not upload photo.')}}
 async function removePhoto(){try{await removeProfilePhoto();await refresh();setData(await getProfile())}catch(e){setMessage(e instanceof Error?e.message:'Could not remove photo.')}}
 async function changePassword(e:FormEvent){e.preventDefault();try{await updatePassword({currentPassword:currentPassword||undefined,newPassword});setPasswordOpen(false);setCurrentPassword('');setNewPassword('');setMessage('Password updated.');setData(await getProfile())}catch(e){setMessage(e instanceof Error?e.message:'Could not update password.')}}
 async function manageSubscription(){try{const portal=await openBillingPortal();window.location.assign(portal.url)}catch(e){setMessage(e instanceof Error?e.message:'Could not open billing portal.')}}
 async function signOut(){await logout();navigate('/login',{replace:true})}
 const u=data?.user||user!; const sub=data?.subscription
 return <main className="profile-page"><section className="profile-hero"><h1>Profile &amp; Settings</h1><p>Manage your account calmly and clearly.</p></section>
  <section className="profile-section"><h2>Profile</h2><div className="profile-photo-row"><div className="profile-avatar">{u.profileImageUrl?<img src={u.profileImageUrl} alt="Profile"/>:initials(u.fullName)}</div><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>photo(e.target.files?.[0])}/><button className="profile-outline" onClick={()=>fileRef.current?.click()}>▣ &nbsp; Change photo</button><button className="profile-remove" onClick={removePhoto}>♙ &nbsp; Remove</button></div>
   <form className="profile-form" onSubmit={save}><label>NAME<input value={name} onChange={e=>setName(e.target.value)}/></label><label>EMAIL<input value={u.email} disabled/></label><label>PHONE NUMBER<div className="profile-phone"><span>🇮🇳⌄</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91"/></div></label><div/><div className="profile-save-row"><button className="profile-primary">Save changes</button><span>JPG, PNG, and WebP profile photos up to 5 MB are supported.</span></div></form>{message&&<p className="profile-message">{message}</p>}</section>
  <section className="profile-section profile-security"><h2>Security</h2><div><b>{u.hasPassword?'Change password':'Create password'}</b><button className="profile-outline" onClick={()=>setPasswordOpen(true)}>{u.hasPassword?'Change':'Create'}</button></div></section>
  <section className="profile-section"><h2>Subscription</h2><p>A single monthly plan, clearly presented and easy to manage.</p><div className="subscription-cards"><div><span>PLAN</span><b>${Number(sub?.monthlyPrice??8.99).toFixed(2)} / month</b></div><div><span>STATUS</span><b>{sub?.status==='ACTIVE'?'Active':'Inactive'}</b></div><div><span>NEXT BILLING</span><b>{dateText(sub?.currentPeriodEnd)}</b></div></div><div className="manage-row"><div><b>Manage subscription</b><p>Review billing details, payment method, or plan renewal settings.</p></div><button className="profile-primary" type="button" onClick={manageSubscription}>Manage</button></div></section>
  <section className="profile-section profile-account"><h2>Account</h2><div><b>Logout</b><button className="profile-remove" onClick={signOut}>⇥ &nbsp; Logout</button></div></section>
  {passwordOpen&&<div className="password-modal-backdrop" onMouseDown={()=>setPasswordOpen(false)}><form className="password-modal" onSubmit={changePassword} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-x" onClick={()=>setPasswordOpen(false)}>×</button><div className="modal-key">⚿</div><small>SECURITY</small><h2>{u.hasPassword?'Change password':'Create password'}</h2><p>{u.hasPassword?'Enter your current password and choose a new one for your account.':'Create a password so you can also sign in with email.'}</p>{u.hasPassword&&<label>CURRENT PASSWORD<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required/></label>}<label>NEW PASSWORD<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label><div className="modal-actions"><button type="button" className="profile-outline" onClick={()=>setPasswordOpen(false)}>Not Now</button><button className="modal-update">{u.hasPassword?'Update Password':'Create Password'}</button></div></form></div>}
 </main>
}
