import { Link } from 'react-router-dom'
import { MiniCardGrid, PageHeader, Panel, Stat } from '../../components/app/PagePrimitives'

export function AdminDashboard(){return <><PageHeader eyebrow="Admin panel" title="Dashboard" copy="Overview of cards, members, requests, and orders."/><div className="stat-grid"><Stat label="Members" value="2,408" note="+8.4% this month"/><Stat label="Cards" value="684"/><Stat label="Open requests" value="31"/><Stat label="Revenue" value="$18.6k"/></div><div className="two-column"><Panel title="Recent orders"><AdminTable type="orders"/></Panel><Panel title="Latest activity"><Activity/></Panel></div></>}
export function AdminCards(){return <><PageHeader eyebrow="Content" title="Cards management" copy="Create, edit, publish, lock, and organise poetry cards." action={<Link className="button" to="/admin/cards/new">Create Card</Link>}/><div className="filter-row"><button>All</button><button>Published</button><button>Draft</button><button>Locked</button></div><MiniCardGrid/><MiniCardGrid/></>}
export function AdminCreateCard(){return <><PageHeader eyebrow="Cards management" title="Create card" copy="Compose the front and back, then preview before publishing."/><div className="admin-editor"><Panel title="Card content"><label className="field">Category<select><option>Love</option><option>Birthday</option></select></label><label className="field">Title<input defaultValue="Still Choosing You"/></label><label className="field">Poetry<textarea rows={8} defaultValue="Every day, I choose you all over again."/></label><button className="button">Save card</button></Panel><article className="large-poem theme-forest inverse"><span className="pill">Love</span><div><h2>Still Choosing You</h2><p>Every day, I choose you all over again.</p></div><small>Preview · Front</small></article></div></>}
export function AdminCreateCardBack(){return <><PageHeader eyebrow="Cards management" title="Create card · Back" copy="Configure personal message space and card attribution."/><div className="admin-editor"><Panel title="Back content"><label className="field">Prompt<input defaultValue="Add your own message"/></label><label className="field">Footer<input defaultValue="Verse & Feeling™"/></label><button className="button">Save card</button></Panel><article className="large-poem theme-sand"><div><p className="center">A place for your own meaningful words.</p></div><small>Preview · Back</small></article></div></>}
export function AdminBulkUpload(){return <><PageHeader eyebrow="Cards management" title="Bulk upload cards" copy="Upload a structured spreadsheet to create several cards at once."/><Panel><div className="drop-zone"><strong>Drop Excel or CSV file here</strong><p>Required columns: category, title, poem, theme, access.</p><button className="secondary-button">Choose File</button></div></Panel></>}
export function AdminBulkUploadReview(){return <><PageHeader eyebrow="Cards management" title="Review bulk upload" copy="12 rows found · 2 require attention"/><AdminTable type="upload"/><button className="button">Import valid rows</button></>}
export function AdminUsers(){return <><PageHeader eyebrow="People" title="Users management" copy="View accounts, plans, status, and activity."/><AdminTable type="users"/></>}
export function AdminSubscriptions(){return <><PageHeader eyebrow="Billing" title="Subscriptions and payments" copy="Monitor recurring plans, payments, and cancellations."/><div className="stat-grid"><Stat label="Active subscriptions" value="1,986"/><Stat label="Monthly revenue" value="$17,855"/><Stat label="Churn" value="2.1%"/></div><AdminTable type="subscriptions"/></>}
export function AdminPoetryRequests(){return <><PageHeader eyebrow="Custom poetry" title="Poetry requests" copy="Assign writers and move requests through review."/><AdminTable type="requests"/></>}
export function AdminPoetryRequestDetail(){return <><PageHeader eyebrow="Request PR-1042" title="Anniversary poem" copy="Assigned to Olivia · Due 12 May"/><div className="two-column"><Panel title="Customer brief"><p className="article-copy">A warm anniversary poem celebrating twenty years of marriage, shared travel, and quiet daily rituals.</p></Panel><Panel title="Workflow"><label className="field">Status<select><option>In progress</option><option>Review</option><option>Complete</option></select></label><label className="field">Internal note<textarea rows={6}/></label><button className="button">Update request</button></Panel></div></>}
export function AdminOrders(){return <><PageHeader eyebrow="Commerce" title="Orders list" copy="Manage fulfilment, shipping, and delivery status."/><AdminTable type="orders"/></>}
export function AdminOrderDetail(){return <><PageHeader eyebrow="Order VF-2091" title="Order detail" copy="Premium printed card · Express delivery"/><div className="two-column"><Panel title="Customer"><p>Amelia Hart<br/>amelia@example.com<br/>London, United Kingdom</p></Panel><Panel title="Fulfilment"><label className="field">Status<select><option>Shipped</option><option>Delivered</option></select></label><label className="field">Tracking<input defaultValue="VF238490203"/></label><button className="button">Save status</button></Panel></div></>}
export function AdminNotifications(){return <><PageHeader eyebrow="Communication" title="Notifications" copy="Create and review customer-facing announcements." action={<button className="button">New Notification</button>}/><Activity/></>}
export function AdminCommunity(){return <><PageHeader eyebrow="Moderation" title="Community" copy="Review forum posts and reported content."/><AdminTable type="community"/></>}
export function AdminCommunityReview(){return <><PageHeader eyebrow="Moderation queue" title="Review post" copy="Reported for possible promotional content."/><Panel><h2>The words we keep returning to</h2><p className="article-copy">Some poems stay with us because they arrive at exactly the right moment...</p><div className="button-row"><button className="button">Approve</button><button className="danger-button">Remove</button></div></Panel></>}
export function AdminSettings(){return <><PageHeader eyebrow="Configuration" title="System settings" copy="Manage branding, plans, email, and platform preferences."/><div className="settings-stack"><Panel title="Branding"><label className="field">Site name<input defaultValue="Verse & Feeling"/></label><label className="field">Support email<input defaultValue="hello@verseandfeeling.com"/></label></Panel><Panel title="Subscription"><label className="field">Monthly price<input defaultValue="$8.99"/></label><label className="field">Trial period<input defaultValue="0 days"/></label></Panel><button className="button">Save settings</button></div></>}
function Activity(){return <div className="activity-list">{['New poetry request submitted','Order VF-2091 marked shipped','Card “Quiet Celebration” published','New member subscription'].map((x,i)=><div key={x}><span>0{i+1}</span><p>{x}<small>{i+1} hour ago</small></p></div>)}</div>}
function AdminTable({type}:{type:string}){const rows:Record<string,string[][]>={orders:[['VF-2091','Amelia Hart','Shipped','$16.00'],['VF-2088','Noah James','Processing','$12.00'],['VF-2081','Mia Chen','Delivered','$18.00']],users:[['Maya Singh','maya@example.com','Active','Monthly'],['Olivia Reed','olivia@example.com','Active','Annual'],['Noah James','noah@example.com','Paused','Monthly']],subscriptions:[['SUB-901','Maya Singh','$8.99','Paid'],['SUB-900','Olivia Reed','$89.00','Paid'],['SUB-899','Noah James','$8.99','Failed']],requests:[['PR-1042','Anniversary','In progress','Olivia'],['PR-1038','Birthday','Review','Maya'],['PR-1029','Love','New','Unassigned']],community:[['The words we keep returning to','Maya','12 replies','Review'],['A card that changed a day','Noah','8 replies','Published']],upload:[['1','Love','Still Choosing You','Valid'],['2','Birthday','Quiet Celebration','Valid'],['3','Anniversary','','Missing title']]};return <div className="data-table admin-data">{(rows[type]||rows.orders).map((r,i)=><div className="data-row" key={i}>{r.map(x=><span key={x}>{x}</span>)}<button className="table-action">View</button></div>)}</div>}
